# host: Host where the database server is located
# user: Username to log in as
# password: Password to use.
# port: MySQL port to use.
# database: Database to use, None to not use a particular one.
host: 'haulistix-dev.cj3nslaldrrf.us-west-1.rds.amazonaws.com'
user: 'elevate'
password: 'FkqN9ALcTsqIH3fC'
port: 53306
database: 'beyondtrucks_test'